version: "3.4"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: apartment
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    links:
      - mongodb:mongo
    environment:
      - HOST=0.0.0.0
